feat: add apiVersion
salesforcecli/plugin-org pull request #580
Opened 2023-02-13 20:04 UTC by mshanemc

### What does this PR do?
add api version to the org display output

### What issues does this PR fix or reference?
@W-12538222@

2023-02-13 22:55 UTC, WillieRuemmele approved these changes

2023-02-13 23:49 UTC, WillieRuemmele commented
### QA Notes
---

✅ : ` Api Version     56.0  ` in table
✅ : `    "apiVersion": "56.0",` in `--json`

2023-02-14 12:36 UTC, cristiand391 requested changes
regenerate the json schemas to add the new field.
```
➜  plugin-org git:(sm/apiVersion-in-org-display) yarn run test:json-schema
yarn run v1.22.19
$ wireit
🏃 [test:json-schema] Running command ""./bin/dev" schema:compare"

Found the following schema changes:

commands.org:display
  - definitions.OrgDisplayReturn.properties.apiVersion was not found in latest
 schema

If intended, please update the schema file(s) and run again: bin/dev schema:generate
❌ [test:json-schema] Failed with exit status 1
error Command failed with exit code 1
```

2023-02-14 15:01 UTC, cristiand391 approved these changes

2023-02-14 15:51 UTC, merged